In [3]:
import numpy as np

## 1. DataTypes & Attributes

In [4]:
# NumPy's main datatype is ndarray (n dimentional array)
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3], [4,5,6]])
a3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
a4 = np.array([[[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]], [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
a3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [8]:
a4

array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]])

In [10]:
a1.shape, a2.shape, a3.shape, a4.shape

((3,), (2, 3), (2, 2, 3), (2, 2, 2, 3))

In [11]:
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 2, 3, 4)

In [14]:
a1.dtype, a2.dtype, a3.dtype, a4.dtype

(dtype('int32'), dtype('int32'), dtype('int32'), dtype('float64'))

In [15]:
a1.size, a2.size, a3.size, a4.size

(3, 6, 12, 24)

In [16]:
type(a1), type(a2), type(a3), type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# Create a DataFrame from a NumPy array
import pandas as pd

df1 = pd.DataFrame(a1)
df2 = pd.DataFrame(a2)

In [20]:
df1

0
0  1
1  2
2  3

In [22]:
df2

0  1  2
0  1  2  3
1  1  2  3

## 2. Creating arrays

In [23]:
sample_array = np.array([1,2,3])

In [24]:
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int32')

In [26]:
ones = np.ones((2, 3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
zeros = np.zeros((2, 3))

In [29]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
range_array = np.arange(0, 10, 2)

In [31]:
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array = np.random.randint(0, 100, size=(3, 5))

In [35]:
random_array

array([[80, 75, 33, 46, 34],
       [68, 46, 20, 92, 12],
       [21, 51, 86, 31, 86]])

In [4]:
np.random.seed(7)
random_array_int = np.random.randint(10, size=(5, 3))
random_array_int

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

## 3. Viewing arrays and matrices

In [6]:
np.unique(random_array_int)

array([3, 4, 6, 7, 8, 9])

In [9]:
a1[0]

1

In [10]:
a3[0]

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
a3[0,1]

array([1, 2, 3])

In [13]:
a3[0,1,1]

2

In [25]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
# This is called: slicing
a3[:, :, :1]

array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [28]:
a1

array([1, 2, 3])

In [29]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [30]:
a1 + ones

array([2., 3., 4.])

In [31]:
a1 * ones

array([1., 2., 3.])

In [32]:
a1 - ones

array([0., 1., 2.])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [39]:
a2 * a3

array([[[ 1,  4,  9],
        [16, 25, 36]],

       [[ 7, 16, 27],
        [40, 55, 72]]])

In [40]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [42]:
## Floor division removes the decimals (rounds down)
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [43]:
np.add(a1, ones)

array([2., 3., 4.])

In [44]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [45]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

##### Aggregation = Performing the same operation on a number of things

In [1]:
listy_list = [1,2,3]
sum(listy_list)

6

In [5]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [6]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [7]:
massive_array[:10]

array([0.72077263, 0.10497961, 0.39365472, 0.79396919, 0.88976648,
       0.60898102, 0.46745062, 0.79441682, 0.41607896, 0.57021253])

In [9]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy np.sum()

13.9 ms ± 308 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
41.9 µs ± 693 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.mean(a2)

3.5

In [12]:
np.max(a2)

6

In [13]:
np.min(a2)

1

In [14]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean 
np.std(a2)

1.707825127659933

In [15]:
# Variance = measure of the average degree to which each number is differente to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

2.9166666666666665

In [16]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.707825127659933